from fpdf import FPDF
import unicodedata

def clean_text(text):
    return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('ascii')

def generate_resume_pdf(name, email, phone, linkedin, profile, education, projects, skills, soft_skills, extras):
    pdf = FPDF()
    pdf.add_page()

    # 🎨 Background
    pdf.set_fill_color(248, 248, 255)  # very light lavender
    pdf.rect(0, 0, 210, 297, 'F')

    # 🔹 Top bar
    pdf.set_fill_color(52, 73, 94)  # dark navy
    pdf.rect(0, 0, 210, 20, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 16)
    pdf.set_xy(10, 6)
    pdf.cell(0, 8, name.title(), ln=True, align='L')
    pdf.set_font("Arial", '', 10)
    pdf.set_x(10)
    pdf.cell(0, 6, f"{email} | {phone} | {linkedin}", ln=True, align='L')
    pdf.ln(6)

    # ✏ Helper to add boxed section
    def boxed_section(title, content):
        pdf.set_fill_color(255, 255, 255)  # white box
        pdf.set_text_color(231, 76, 60)  # crimson heading
        pdf.set_font("Arial", 'B', 12)
        pdf.multi_cell(0, 8, title, border=1, align='L', fill=True)
        pdf.ln(1)
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Arial", '', 11)
        pdf.multi_cell(0, 6, content, border=1, align='L', fill=True)
        pdf.ln(3)

    # 📝 Add sections
    boxed_section("Career Objective", clean_text(profile))

    # 🏫 Education: modify to split lines nicely
    edu_lines = education.split('\n')
    clean_edu = ""
    for line in edu_lines:
        if 'Branch' in line or 'CGPA' in line or 'Year' in line:
            # skip old style
            continue
        elif 'at' in line:
            # convert "Branch: CSE, CGPA: 8, Year: 2026 at UCER Prayagraj"
            parts = line.split('at')
            college = parts[-1].strip()
            before = parts[0]
            branch = ""
            cgpa = ""
            year = ""
            if 'Branch:' in before:
                branch = before.split('Branch:')[-1].split(',')[0].strip()
            if 'CGPA:' in before:
                cgpa = before.split('CGPA:')[-1].split(',')[0].strip()
            if 'Year:' in before:
                year = before.split('Year:')[-1].strip()
            clean_edu += f"• {college} (B.Tech {branch})\n"
            if cgpa: clean_edu += f"• CGPA: {cgpa}\n"
            if year: clean_edu += f"• Year of completion: {year}\n"
        else:
            clean_edu += f"{line}\n"

    boxed_section("Education", clean_text(clean_edu.strip()))
    boxed_section("Academic Projects", clean_text(projects))
    boxed_section("Technical Skills", clean_text(skills))
    boxed_section("Soft Skills", clean_text(soft_skills))
    boxed_section("Extra-Curricular Activities", clean_text(extras))

    # Footer
    pdf.set_y(-15)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(120,120,120)
    pdf.cell(0, 10, 'Generated by AI Resume Builder', 0, 0, 'C')

    file_name = "resume.pdf"
    pdf.output(file_name)
    return file_name

def generate_cover_letter_pdf(name, email, phone, linkedin, cover_letter):
    pdf = FPDF()
    pdf.add_page()

    # Light grey background
    pdf.set_fill_color(245, 245, 245)
    pdf.rect(0, 0, 210, 297, 'F')

    # Maroon title bar
    pdf.set_fill_color(128, 0, 0)
    pdf.rect(0, 0, 210, 20, 'F')
    pdf.set_text_color(255,255,255)
    pdf.set_font("Arial", 'B', 16)
    pdf.set_xy(10, 6)
    pdf.cell(0, 8, f"{name.title()} – Cover Letter", ln=True)
    pdf.set_font("Arial", '', 10)
    pdf.set_x(10)
    pdf.cell(0, 6, f"{phone} | {email} | {linkedin}", ln=True)
    pdf.ln(6)

    pdf.set_text_color(40,40,40)
    pdf.set_font("Arial", '', 12)
    pdf.multi_cell(0, 7, clean_text(cover_letter))

    pdf.set_y(-15)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(120,120,120)
    pdf.cell(0, 10, 'Generated by AI Resume Builder', 0, 0, 'C')

    file_name = "cover_letter.pdf"
    pdf.output(file_name)
    return file_name

